/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PrintFormFieldComponent {
    /**
    * Filled in text
    */
    'filledText': string;
    /**
    * Form field description
    */
    'introText': string;
    /**
    * Underline notes
    */
    'notes': string;
    /**
    * Symbol that separates notes in string
    */
    'notesSeparator': string;
  }
}

declare global {


  interface HTMLPrintFormFieldComponentElement extends Components.PrintFormFieldComponent, HTMLStencilElement {}
  var HTMLPrintFormFieldComponentElement: {
    prototype: HTMLPrintFormFieldComponentElement;
    new (): HTMLPrintFormFieldComponentElement;
  };
  interface HTMLElementTagNameMap {
    'print-form-field-component': HTMLPrintFormFieldComponentElement;
  }
}

declare namespace LocalJSX {
  interface PrintFormFieldComponent {
    /**
    * Filled in text
    */
    'filledText'?: string;
    /**
    * Form field description
    */
    'introText'?: string;
    /**
    * Underline notes
    */
    'notes'?: string;
    /**
    * Symbol that separates notes in string
    */
    'notesSeparator'?: string;
  }

  interface IntrinsicElements {
    'print-form-field-component': PrintFormFieldComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'print-form-field-component': LocalJSX.PrintFormFieldComponent & JSXBase.HTMLAttributes<HTMLPrintFormFieldComponentElement>;
    }
  }
}


