/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FormFieldComponent {
    /**
    * Filled in text
    */
    'filledText': string;
    /**
    * Form field description
    */
    'introText': string;
    /**
    * Underline notes
    */
    'notes': string;
    /**
    * Symbol that separates notes in string
    */
    'notesSeparator': string;
  }
}

declare global {


  interface HTMLFormFieldComponentElement extends Components.FormFieldComponent, HTMLStencilElement {}
  var HTMLFormFieldComponentElement: {
    prototype: HTMLFormFieldComponentElement;
    new (): HTMLFormFieldComponentElement;
  };
  interface HTMLElementTagNameMap {
    'form-field-component': HTMLFormFieldComponentElement;
  }
}

declare namespace LocalJSX {
  interface FormFieldComponent {
    /**
    * Filled in text
    */
    'filledText'?: string;
    /**
    * Form field description
    */
    'introText'?: string;
    /**
    * Underline notes
    */
    'notes'?: string;
    /**
    * Symbol that separates notes in string
    */
    'notesSeparator'?: string;
  }

  interface IntrinsicElements {
    'form-field-component': FormFieldComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'form-field-component': LocalJSX.FormFieldComponent & JSXBase.HTMLAttributes<HTMLFormFieldComponentElement>;
    }
  }
}


